### ISSUE TITLE
1.9 Update Bug-Tracker

### ISSUE THREAD

**Issue by sebastianbinder** [Yannici/bedwars-reloaded#447]
## In Progress
- [ ] Fix old shop
- Type: ``Bug``
- Description: Old shop is not completely working
- Responsible: @Yannici

### Important
``none``

### Not Important (doesn't need to be included in the next version)

- [ ] PlayerInteractEvent
- Type: ``Improvement``
- Description: Since 1.8 this event is getting called twice - left or right hand needs to be specified
- Further Information: https://hub.spigotmc.org/jira/browse/SPIGOT-1570
- Responsible: ``open``

## Done
- [x] Potions
- Type: ``Bug``
- Description: Generating potion with simple meta tags isn't working anymore. Update Potions to use PotionMeta
- Responsible: @sebastianbinder

- [x] Plugin-Updater
- Type: ``Feature``
- Description:  Plugin Updater needs to support the Minecraft 1.7 version drop
- Responsible: @ sebastianbinder

- [x] TNT-Sheep
- Type: ``Bug``
- Description:  Sheep do not really follow players, just pretty slow and not direct way to player
- Responsible: @Yannici

- [x] LeftHandEvent
- Type: ``Improvement``
- Description: Lobby Inventory could get in left hand - needs to be blocked
- Further Information: https://hub.spigotmc.org/jira/browse/SPIGOT-1532
- Responsible: @sebastianbinder

## No BedwarsRel Bugs
- [x] Tablist without team colors (Spigot Bug - fixed: https://hub.spigotmc.org/jira/browse/SPIGOT-1624)
- [x] Scoreboard not updating on bed destroy (wrong sound in config for bed destroy was the problem)
- [x] Gamemode 3 cannot fly through blocks (Bungeecord Bug - fix: https://hub.spigotmc.org/jira/browse/SPIGOT-1629)
- [x] http://pastebin.com/htH5BnAD -> fixed in https://hub.spigotmc.org/jira/browse/SPIGOT-1598

**Comment by sebastianbinder** [comment]
Als Gedächtnisstütze eine kleine Sammlung für mich...
- [] Spieler haben in Tab-Liste keine Farbe
- [] Scoreboard wird beim Bett-Abbauen nicht geupdatet (evtl. wg. falschem Sound in Config bisher)
- [] Gamemode 3: Fliegen durch Wände nicht möglich (evtl. wg. fehlerhaftem AAC)

**Comment by Granik24** [comment]
You maybe should write this in English I think..

**Comment by sebastianbinder** [comment]
Sorry for that - gonna translate it soon, but right now while testing it is a lot easier for me in German...

**Comment by sebastianbinder** [comment]
@Yannici - can you have a look on the Sheep thing?

**Comment by Yannici** [comment]
Yes, I will check that.

**Comment by sebastianbinder** [comment]
Potion with simple meta-data isn't supported in 1.9 anymore.
Need to change the way of buying potions.

What do you think - is this way of configuring a potion item in shop okay? A simple heal-potion could look like this:
```yml
           - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                name: 'Heal Potion'
                item: 373
                amount: 1
                effects:
                  - type: HEAL
```
But you can also add duration and amplifier:
```yml
           - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                name: 'Potion of Regeneration II'
                item: 373
                amount: 1
                effects:
                  - type: REGENERATION
                    duration: 20
                    amplifier: 2
```
Or combine multiple effects:
```yml
           - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                name: 'Special Potion'
                item: 373
                amount: 1
                effects:
                  - type: HEAL
                  - type: Absorption
                    duration: 40
                    amplifier: 2
                  - type: REGENERATION
                    duration: 10
                    amplifier: 2
```

Pro: potions work again and you can make more special potions
Con: everybody upgrading to BedwarsRel 1.3.0 needs to update his shop

What do you guys think?

**Comment by Block-Build** [comment]
Is this 1.8 compatible too?

**Comment by Yannici** [comment]
The solution is good. Maybe we can implement a upgrade function which will upgrade the shop.yml automatically to the new potion solution.

**Comment by sebastianbinder** [comment]
>> Is this 1.8 compatible too?

@Block-Build - Yes, I tested both 1.8 and 1.9

>> The solution is good. Maybe we can implement a upgrade function which will upgrade the shop.yml automatically to the new potion solution.

@Yannici - Okay, I'm gonna push my code then. An updater would be nice, but you know … my java skills … we should integrate it with the config updater … feel free to have a look on it if you have any spare time for that :)

**Comment by HobbyzockerLP** [comment]
Nice! :)

**Comment by HobbyzockerLP** [comment]
Where i can download the new Version?

**Comment by sebastianbinder** [comment]
@HobbyzockerLP Just download the sources and build it with Ant.

**Comment by HobbyzockerLP** [comment]
Also muss ich selber den code ändern?

**Comment by Yannici** [comment]
Ja, aktuell gibt es noch keinen Build für die 1.9-Version.

**Comment by HobbyzockerLP** [comment]
Then I need help^^

**Comment by Block-Build** [comment]
@HobbyzockerLP I think you can find it on @sebastianbinder Jenkin site

**Comment by sebastianbinder** [comment]
No. There simply is no build yet, since we are not done with fixing all the errors. Everyone who would like to test the beta needs to know how to build it with Ant.

**Comment by HobbyzockerLP** [comment]
Do it for me, please :D

**Comment by Yannici** [comment]
@HobbyzockerLP Please be patient!

**Comment by komiss77** [comment]
Hi, Yannici! 
I've set up [your plugin](http://ostrov77.ru/uploads/bedwars.zip) to work with 1.9. All works, except TNTsheep. 
Look, maybe something useful to you and can make your job easier.
 Excuse me beforehand that made your code ugly)

**Comment by sebastianbinder** [comment]
@komiss77 So if you didn't fix the sheep, what exactly did you do then?

**Comment by komiss77** [comment]
Just people ask the beta version for 1.9.
  This can be used, in addition, there are some improvements (Spectator mode, rescue platform, etc.)

**Comment by sebastianbinder** [comment]
@komiss77 So please fork the project from here, then upload the code to your github branch and open a pull request. This makes it a lot easier for us to review your changes and implement them into the project.

**Comment by Yannici** [comment]
@komiss77 Stop uploading my plugin on your own page. This is not allowed. Please create an pull request.

**Comment by komiss77** [comment]
@Yannici I do not upload nothing on my own page. Code changed on local PC in NetBeans only for test and try to help you.

**Comment by Yannici** [comment]
@komiss77 No problem, just saying. Try to fork and make a pull request please.

**Comment by sebastianbinder** [comment]
Added tipped arrow support, use effects in the same way as potions:
```yml
            - item1:
                item: IRON_INGOT
                amount: 2
              reward:
                item: 440
                amount: 10
                effects:
                  - type: REGENERATION
                    duration: 45
                  - type: INCREASE_DAMAGE
                    duration: 180
                    amplifier: 5
```

**Comment by sebastianbinder** [comment]
Just made changes to the plugin updater. For Minecraft version 1.7, updater reads first line of release.txt, for version 1.8 and 1.9 it reads second line.
@Yannici: Is that enough for solving this issue or does anything else need to be changed here? You know the updater better than I do :P

**Comment by Yannici** [comment]
@sebastianbinder https://github.com/Yannici/bedwars-reloaded/commit/742a13fbf221f69b1eeed54695e0783e18443b96 test please ;)
Made a little improvement of the updater, but looks good ... :)

**Comment by sebastianbinder** [comment]
@Yannici - Just tried it locally - seems to work. Put it on my server now and I'll give you some more feedback after 24 hours in "live" environment.

**Comment by Yannici** [comment]
Okay ;) Thanks.

**Comment by sebastianbinder** [comment]
@Yannici - final test result: works perfectly :)

**Comment by partydragen** [comment]
Will BedwarsRel soon be fixed for 1.9? I running a network and bedwars is 1.8 only since the game not starting with 1.9 Only spamming Game starting in 10 sec

**Comment by sebastianbinder** [comment]
@partydragen I'm sure you can read - so simply have a proper look on this issue here. Then you'll see that we are working on the release :/

**Comment by partydragen** [comment]
Can't See anything here what shold effect the game from starting Every things i see is much potions and sheep and things

But why i hear its working for others to start the game D;
I need to remove the potions from shop? or some things

Sorry for my english Im Norwegian

**Comment by sebastianbinder** [comment]
@partydragen If you are having issues others don't have and they are still there after we released the 1.9 compatible version, feel free to open a new issue and we gonna try to help you. If you think this is a problem we haven't seen yet, then we need more details about your setup.

**Comment by sebastianbinder** [comment]
Potions seem to be broken again in newest Spigot builds. May be caused by this commit to spigot: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/4a8818c5fd4be406c59b518b86f10f39b4e6dcdd
Gonna have a look on it later this day...

**Comment by Yannici** [comment]
Ok, I think we should really wait until the 1.9 will have an stable build ... Otherwise we maybe have to release a new version every 2 weeks :/

**Comment by sebastianbinder** [comment]
@Yannici Just fixed the way potions are being generated - but they still throw an error as soon as you try to buy them. Do you have an idea? http://pastebin.com/TAvuF9RY

**Comment by Yannici** [comment]
@sebastianbinder Did you debug the code? To find out on which statement it will crash?

**Comment by sebastianbinder** [comment]
Potions now can be bought again **in new shop** - the old one doesn't work at all for potions. I really don't know where to start here @Yannici 
Furthermore I decided for better backwards compatibility to add the old potion meta support for Minecraft 1.8 again:
In 1.8 you can use the "meta" in your shop for generating all the "standard potions". Instead of using meta you can use the new way with multiple effects **BUT** this only works for non-splash potions in 1.8 (that's the reason I added the old way again).
In 1.9 only the new way works (with potion and the new Materials "splash_potion" and "lingering_potion").

**Comment by partydragen** [comment]
Some here can can create that jar for me? With these latest commits? I know its not work perfekt but maybe working for 1.9

**Comment by sebastianbinder** [comment]
Just added ``PlayerSwapHandItemsEvent`` (thanks to latest Spigot API) which means that swapping items to off-hand is now impossible in lobby.

**Comment by partydragen** [comment]
How long before a new build? Days, Weeks months??

**Comment by partydragen** [comment]
Any plannes when its will be a new build or release for 1.9 that just work without potions since its not working but not important Or i need to change to the Another bedwars plugin ;/

**Comment by Block-Build** [comment]
@partydragen please wait. There is no specific release date.

**Comment by sebastianbinder** [comment]
```
[16:22:43 WARN]: java.lang.IllegalArgumentException: Can not set boolean field net.minecraft.server.v1_9_R1.EntityVillager.by to java.lang.Integer
[16:22:43 WARN]:        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[16:22:43 WARN]:        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[16:22:43 WARN]:        at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(UnsafeBooleanFieldAccessorImpl.java:86)
[16:22:43 WARN]:        at java.lang.reflect.Field.set(Field.java:764)
[16:22:43 WARN]:        at io.github.yannici.bedwars.Com.v1_9_R1.VillagerItemShop.createVillager(Unknown Source)
[16:22:43 WARN]:        at io.github.yannici.bedwars.Com.v1_9_R1.VillagerItemShop.access$000(Unknown Source)
[16:22:43 WARN]:        at io.github.yannici.bedwars.Com.v1_9_R1.VillagerItemShop$1.run(Unknown Source)
[16:22:43 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[16:22:43 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[16:22:43 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[16:22:43 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[16:22:43 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[16:22:43 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[16:22:43 WARN]:        at java.lang.Thread.run(Thread.java:745)
[16:22:43 WARN]: java.lang.NullPointerException
[16:22:43 WARN]:        at io.github.yannici.bedwars.Com.v1_9_R1.VillagerItemShop$1.run(Unknown Source)
[16:22:43 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[16:22:43 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[16:22:43 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[16:22:43 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[16:22:43 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[16:22:43 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[16:22:43 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by partydragen** [comment]
thata bad? ;/

**Comment by sebastianbinder** [comment]
@Yannici
Field ``by`` in ``EntityVillager`` is a ``boolean``, so
```java
## io.github.yannici.bedwars.Com.v1_9_R1.VillagerItemShop ##
Field careerField = EntityVillager.class.getDeclaredField("by");
careerField.setAccessible(true);
careerField.set(ev, Integer.valueOf(10));
```
throws the error and makes the old shop completely not working anymore. Any ideas on fixing this?

**Comment by Yannici** [comment]
The field was standing for the type of the villager (farmer, librarian, priest ...).
I don't know if this is important, so just try to remove these lines ;-) It should work ...

**Comment by partydragen** [comment]
Only the old shop is effected? Why not just remove it? :/ And fix it overtime I can't wait anymore D: The another bedwars plugin used little time only

**Comment by Yannici** [comment]
Many people using the old shop. So no, we won't remove it.

**Comment by sebastianbinder** [comment]
@Yannici 
> I don't know if this is important, so just try to remove these lines ;-) It should work …

Just tried it - even if it doesn't throw the error anymore, old shop is still not working.

**Comment by Yannici** [comment]
What exactly is not working?

**Comment by HobbyzockerLP** [comment]
The old shop should remain!

**Comment by Dimatert9** [comment]
How i can fix sound error?

**Comment by Dimatert9** [comment]
[15:12:46] [Server thread/WARN]: java.lang.NullPointerException
[15:12:46] [Server thread/WARN]: 	at io.github.yannici.bedwars.Com.v1_9_R1.VillagerItemShop$1.run(Unknown Source)
[15:12:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[15:12:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[15:12:46] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[15:12:46] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[15:12:46] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[15:12:46] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[15:12:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:12:46] [Server thread/ERROR]: Could not pass event BlockBreakEvent to BedwarsRel v1.3.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:846) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [Spigot.jar:git-Spigot-0426685-4cd46b2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.ENDERDRAGON_GROWL
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_74]
	at org.bukkit.Sound.valueOf(Sound.java:1) ~[Spigot.jar:git-Spigot-0426685-4cd46b2]
	at io.github.yannici.bedwars.Game.Game.handleDestroyTargetMaterial(Unknown Source) ~[?:?]
	at io.github.yannici.bedwars.Listener.BlockListener.onBreak(Unknown Source) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-0426685-4cd46b2]
	... 17 more

**Comment by sebastianbinder** [comment]
@Dimatert9 just wait for a 1.9 compatible version of Bedwars-Rel being released

**Comment by partydragen** [comment]
Sorry can't waiy anymore its soon a months ago since 1.9 got released i think i need to try Bedwars since its working for 1.9 ;/ If we get no builds here that work with 1.9 self potions is broken we can just remove them from shop

**Comment by sebastianbinder** [comment]
@partydragon
It's quite easy: If you don't know know how to build the plugin yourself you have the possibility to wait or just use another bedwars plugin.
If you are not happy about the work that is done by us you also have two possibilities: do it yourself better (the project is open source, so fork the project, implement the remaining fixes and open a pull request) or use another bedwars plugin. But do not put any more pressure on us. It is pretty annoying.

**Comment by partydragen** [comment]
Sorry but looks Potions meta working again after i updated to latest spigot version now ;O Looks like every plugins who used potion:Number working again and spawner eggs

**Comment by sebastianbinder** [comment]
@partydragen Potions are not the problem at the moment. It's the old shop. But obviously you are not properly reading this thread here.

**Comment by Yannici** [comment]
Old shop works now. Now checking potions for old shop.

**Comment by Dimatert9** [comment]
@Yannici I dont can compile plugin.
![image](https://cloud.githubusercontent.com/assets/8667294/14127307/817bd85a-f61f-11e5-916c-9dc5cc184719.png)

**Comment by Yannici** [comment]
Looks like he can't find the c3p0-Library. Please use Maven only. This is the preferred build method. With maven it will download the required sources first and then build.

**Comment by Yannici** [comment]
@sebastianbinder You did a big mistake ... You completly deleted the part for extracting the c3p0 jar out of the plugin-jar. This is required to create database connections because the c3p0 library won't get loaded correctly anymore. You can't just add it as a maven dependency. This will build the plugin, but in runtime the library will never be available ...

**Comment by Yannici** [comment]
We may need a new branch for jenkins builds. Otherwise others cannot add our plugin as an maven dependency. Just have to talk with you about that later @sebastianbinder

**Comment by sebastianbinder** [comment]
@Yannici  TNT-sheep not working with my current spigot and latest Bedwars-Rel build :/

**Comment by Yannici** [comment]
I cannot open that link. Can't login.

**Comment by sebastianbinder** [comment]
@Yannici you need to be registered. but it's not that important. It's a pull request about a SpawnEggMeta being in review, since normal meta tags are not supported for spawn eggs anymore https://hub.spigotmc.org/jira/browse/SPIGOT-1592 (kinda the same like with meta tags for potions) and no one really knows how to create custom spawn eggs now. Seems like the only way at the moment is modifying the NBT data which is used for spawn eggs (http://minecraft.gamepedia.com/Spawn_Egg#Data_values)
I did some debugging so it is not a real "shop" problem, since the item can be bought again as soon as the meta tag is being removed in shop.yml - but we need to fix the way TNT sheep are getting generated.
I'm just wondering why this has been working in first 1.9 releases….

**Comment by Yannici** [comment]
I think we just need to wait. I don't think it is a good idea to think of a new solution, as it is obviously an spigot bug.

**Comment by komiss77** [comment]
Now spawn type creature contains in NBT tags. 
The puzzle over the new mechanism, I suggest simply replace in shop egg appeal to another object (such as EXPLOSIVE_MINECART). And everything works fine again.

How to:

shop.yml
`            - item1:
                item: GOLD_INGOT
                amount: 10
              reward:
                name: '&cTNT-Schaf'
                lore:
                    - "Aktiviere das TNT-Schaf! Es wird"
                    - "auf den nächsten Gegner zugehen"
                    - "und nach 8 Sekunden explodieren!"
                item: EXPLOSIVE_MINECART
#                meta: 91
                amount: 1`

TNTSheep.java
`	@Override
	public Material getItemMaterial() {
		return Material.EXPLOSIVE_MINECART;
	}

	public int getEntityTypeId() {
		return 407;
	}`

TNTSheepListener.java
`		//if(!(inHand.getData() instanceof SpawnEgg)) {return;}

		//if(((SpawnEgg) inHand.getData())..getSpawnedType() != EntityType.SHEEP) {return;}`

Now spawn type creature contains in NBT tags. 
The puzzle over the new mechanism, I suggest simply replace in shop egg appeal to another object (such as EXPLOSIVE_MINECART). And everything works fine again.

How to:

shop.yml
`            - item1:
                item: GOLD_INGOT
                amount: 10
              reward:
                name: '&cTNT-Schaf'
                lore:
                    - "Aktiviere das TNT-Schaf! Es wird"
                    - "auf den nächsten Gegner zugehen"
                    - "und nach 8 Sekunden explodieren!"
                item: EXPLOSIVE_MINECART
#                meta: 91
                amount: 1`

TNTSheep.java
`	@Override
	public Material getItemMaterial() {
		return Material.EXPLOSIVE_MINECART;
	}

	public int getEntityTypeId() {
		return 407;
	}`

TNTSheepListener.java
`		//if(!(inHand.getData() instanceof SpawnEgg)) {return;}

		//if(((SpawnEgg) inHand.getData())..getSpawnedType() != EntityType.SHEEP) {return;}`

**Comment by Yannici** [comment]
But this isn't really the preferred solution for me ... This could be a workaround, if no fix will be released.

**Comment by Yannici** [comment]
My PC is currently down, I'm sorry for any delays in release version for 1.9

**Comment by Yannici** [comment]
What about that old shop bug? Is this still a bug? I may release the 1.3.0 today with my notebook.

**Comment by sebastianbinder** [comment]
@Yannici Old shop generally works. The only thing that doesn't work in old shop is my new potion mechanism. But since potion meta is working fine again, the update can be released without any problems as long as we do not really announce the new potion mechanism until it works :)

**Comment by Yannici** [comment]
@sebastianbinder Okay! So I will release it today evening.

**Comment by Yannici** [comment]
I will release it now. But what about that known issue with TNT-Sheep? Is this still a problem?

**Comment by sebastianbinder** [comment]
It's the missing spawn type thing mentioned above. It is fixed with now allowing any spawn egg being a TNT-sheep. Have you merged all the branches? 1.3.0 version support and drop -> 1.3.0-dev -> master

**Comment by sebastianbinder** [comment]
@Yannici just saw that you already put the update on spigot. Which version did you put there without merging and building the project on jenkins? :P

**Comment by sebastianbinder** [comment]
Thanks to @Yannici for releasing the update!

**Comment by sebastianbinder** [comment]
Gonna close this one here, since we are discussing the potion problem in #508
